debian/control

Needed at build time and run time, since there is no way to automatically
detect the runtime dependency by examining linked libraries.
[endlessm/eos-sdk#861]

Add geoclue-2.0 dependency

---

data/eos-metrics-instrumentation.service.in
src/eos-metrics-instrumentation.c

Launch after event recorder daemon.
Since the metrics instrumentation daemon requires the event recorder
daemon in order to record any events, we make it list the event
recorder daemon as a dependency and ensure that the metrics
instrumentation daemon launches after and closes before the event
recorder daemon. This also helps the shutdown event have enough time to
be persisted to disk by the event recorder daemon since it is recorded
when the instrumentation daemon receives the SIGTERM signal from
systemd.
Flush the system DBus connection on shutdown.
This is important for ensuring that the shutdown event makes it to the
event recorder daemon in time to be flushed to disk before power is cut.
[endlessm/eos-sdk#2906]

Launch after event recorder daemon, and flush the system DBus connection on shutdown.

---

debian/control

New synchronous methods were added to the event recorder API in version
0.3.0. These methods are required in the instrumentation daemon for
robust recording of logout and shutdown.
[endlessm/eos-sdk#3029]

Depend on version 0.3.0+ of event recorder API.

---

configure.ac
src/eos-metrics-instrumentation.c
tests/test-location.py

We currently flush outgoing messages at shutdown but don't wait for the
event recorder daemon to handle those method calls before exiting. This
creates a race condition where systemd can shutdown the event recorder
daemon before it has a chance to handle the pending method calls. We now
instead call the event recorder daemon synchronously when recording the
shutdown event. Since we instruct systemd to shutdown the event recorder
daemon after the instrumentation daemon, this ensures the shutdown event
is not dropped.
We don't need to inhibit shutdown anymore because we can record logout
events synchronously. Treating SIGTERM as a logout of any remaining
users is more robust than treating the PrepareForShutdown signal this
way as it's far less likely that shutdown will be cancelled after …

Use synchronous event recorder API for shutdown and logouts.

---

src/eins-persistent-tally.c
tests/test-persistent-tally.c

In general we don't want to attempt error handling in cases we never
expect to enter because they are very difficult to test. If the
persistent tally key isn't found even though the key file exists, then
most likely either there is a programmer error that we shouldn't mask,
or the key file has been tampered with, and we have little hope of
redemption.
[endlessm/eos-sdk#3040]

Avoid unnecessary error handling.

---

src/eos-metrics-instrumentation.c

We have a tuple here, so we should pass the right type, or we'll hit an
assertion.
[endlessm/eos-sdk#3477]

Fix syntax for g_variant_get() call

---

tests/test-location.py

This test currently assumes the first events recorded by the daemon will
be the location ones. This is not true anymore now that we also record
OS name, version and personality.
Change the code to wait for the specific event UUID instead.
[endlessm/eos-shell#5585]

test-location: don't assume first events are location

---

src/eos-metrics-instrumentation.c

These variants are tuples, so we should use the correct type syntax;
also the "SessionRemoved" signal carries two arguments.
[endlessm/eos-shell#5585]

Fix syntax for g_variant_get()

---

src/eins-location.c
src/eos-metrics-instrumentation.c
tests/test-persistent-tally.c

The shutdown event is unreliable because dirty shutdowns are too
frequent. The uptime event and boot count will help us more reliably
estimate the total time the machine has been on. This value is of
interest because it constitutes the denominator of the connectivity
estimate.
[endlessm/eos-sdk#3741]

Record uptime event and boot count.

---

src/eins-persistent-tally.c
src/eos-metrics-instrumentation.c

All the auxiliary payloads of the uptime events in the metrics databases
are null. We need to handle the case where the persistent tally key file
already exists but does not yet contain the boot_time key.

Fix bug causing null payload for uptime events.

---

src/eins-persistent-tally.c
src/eins-persistent-tally.h
src/eos-metrics-instrumentation.c
tests/test-persistent-tally.c

Previously persistent tally objects were 1:1 with keys in key files, but
this led to race conditions when multiple objects were backed by the
same key file. As a consequence, the boot count incremented very rarely.
Since the boot count is unusable before this commit, we assign a new
event ID to the uptime and shutdown events. This will allow us to
distinguish between events with invalid boot counts and events with
valid boot counts on the server.
[endlessm/eos-sdk#3848]

Fix handling of multiple keys in persistent tally.

---

data/Makefile.am.inc
src/eos-metrics-instrumentation.c

This adds event 6b1c1cfc-bc36-438c-0647-dacd5878f2b3 which is sent once at startup to report the image ID, if present. This is a string such as "eos-eos3.1-amd64-amd64.170115-071322.base" which is saved in an attribute on the root filesystem by the image builder, and allows us to tell the channel that the OS was installed by (eg download, OEM pre-install, Endless hardware, USB stick, etc) and which version was installed. The payload is a single string containing this image ID. Allows machines with deployment-specific images to be found and grouped for metrics analysis purposes.
https://phabricator.endlessm.com/T15063

T15063: send eos-image-version xattr as an event

---

.gitignore
Makefile.am
src/Makefile.am.inc
src/eins-network-id.c
src/eins-network-id.h
src/eos-metrics-instrumentation.c
tools/Makefile.am.inc
tools/eos-network-id.c

Introduce the event `38eb48f8-e131-9b57-77c6-35e0590c82fd` which is recorded at system startup and when we detect a change in the default route.
The auxiliary payload is a 32-bit unsigned integer containing a hash of the ethernet MAC address of the gateway, favouring IPv4 if available, or IPv6 if not. The intention is to provide a value which is opaque and stable which is the same for every system located on the same physical network.
The new `eos-network-id` command prints this ID for user inspection.
https://phabricator.endlessm.com/T16934

T16934: add new network ID event to group machines by location

---

src/eos-metrics-instrumentation.c

Alright... bikeshed challenge accepted...
Given the most interesting values here are 0 or non-zero, this
lends itself to a bitfield quite well.
0: No OEM Windows
1: MSDM (Windows >= 8)
2: SLIC (Windows Vista-ish)
3: Unexpected but could happen
Change the event ID due to the new signature.
https://phabricator.endlessm.com/T18296

change Windows license event to a bitfield

---

src/eins-hwinfo.c
tests/test-hwinfo.c

This was failing on an ARM OBS builder. I don't really care whether we can determine the CPU speed on our OBS builder.
To atone for this slight sin, I added some test data collected from an ARM laptop.
https://phabricator.endlessm.com/T18445

Weaken a hwinfo test

---

src/eins-location.c

We only record location on Solutions images and this category should
include image names starting with 'impact' and 'fnde'. Hardcoding for
the time being until we find a better solution.
https://phabricator.endlessm.com/T27743

location: Hardcode fnde and impact images as Solutions images

---

src/eins-location.c
src/eos-metrics-instrumentation.c

We only record the network ID on Solutions images and this category
should include image names starting with 'impact' and 'fnde'. Hardcoding
for the time being until we find a better solution.
https://phabricator.endlessm.com/T27819

network ID: Hardcode fnde and impact images as Solutions images

---

src/eos-metrics-instrumentation.c

In 2.5.0 we introduced the uptime event because the system shutdown
wasn't useful enough. Among other problems it was missed on "dirty"
shutdowns.
https://github.com/endlessm/eos-metrics-instrumentation/commit/8dfd1e5b9
We don't really need the system shutdown any more, so let's just stop
recording it.
cc @ramcq

Stop recording system shutdowns

---

src/eos-metrics-instrumentation.c

The 'error' variable is declared as g_autoptr(GError), meaning that if
it is non-NULL when it goes out of scope, g_error_free() will be called
on it. On the error path, we currently explicitly call g_error_free(),
and do not clear 'error' after doing so. This is a double-free.
Fortunately, reading /proc/cmdline never fails. Nonetheless, delete the
offending line.

Fix double free in /proc/cmdline error path

---

src/eos-crash-metrics.c

This adds the machine architecture and human-readable OS version to the information submitted about core dumps, and also correctly identifies the booted version of the OS.
https://phabricator.endlessm.com/T29404

Improve coredump data

---

src/Makefile.am.inc
src/eins-location-label.c
src/eins-location-label.h
src/eos-metrics-instrumentation.c
tests/Makefile.am.inc
tests/test-location-label.c

If you use eos-label-location and don't give an answer to one or more of
its questions, you get a file like this:
[Label]
facility = Will's House
city = London
state =
The 'site' page in our branch of gnome-initial-setup similarly writes
empty files like this:
[Label]
id =
city =
state =
street =
country =
facility =
As a result of this second case, over 99% of the rows in our production
table for this event are:
{"id": "", "city": "", "state": "", "street": "", "country": "", "facility": ""}
Handle the first case by ignoring empty fields. Handle the second case
by not reporting a metric if there are no non-empty fields. Test these
cases.
https://phabricator.endlessm.com/T30469

Ignore empty location label keys

---

debian/control

Since EOS is going to remove (Geo)location events, geoclue-2.0 will not
be used anymore and the dependency should be dropped.
https://phabricator.endlessm.com/T31354

Drop geoclue-2.0 dependency

---

src/eins-hwinfo.c
src/eins-hwinfo.h
tests/test-hwinfo.c

Introduce new COMPUTER_HWINFO_EVENT to replace/merge RAM_SIZE_EVENT,
SYSROOT_DISK_SPACE_EVENT and CPU_MODELS_EVENT. Modified corresponding
test plans as well.
https://phabricator.endlessm.com/T32205

hwinfo: Implement combined computer hardware info event

---

src/Makefile.am.inc
src/eins-boottime-source.c
src/eins-boottime-source.h
src/eins-hwinfo.c
tests/Makefile.am.inc

Originally, eos-metrics-instrumentation records the hardware information
after system boots and 24 hours which is measured in monotonic time.
However, it may may or may not count time that the system is suspended.
This patch:
* saves the next record time (current real time + 24 hours) into storage
when the information is recorded.
* checks how many time and wait for first record after each boot.
* records the hardware information every 24 hours after first record
since boot. The 24 hours period is timed with CLOCK_BOOTTIME.
https://phabricator.endlessm.com/T32369

hwinfo: Record hardware information every 24 hours

---

debian/control

Fix typo in debian/control

---

src/eos-metrics-instrumentation.c

Previously, the daemon would ascribe the UID of the calling process, in
this case 0 (root), to the event when aggregating. This new API allows
the caller to override this UID, removing the need for an aggregate key.
https://phabricator.endlessm.com/T33252
Depends on https://github.com/endlessm/eos-metrics/pull/47.

Use start_aggregate_timer_with_uid() for session time

---

src/eos-metrics-instrumentation.c

remove_session() claims:
> /* The timer will stop itself when its reference count falls to 0. */
This is technically true, but previously removing the timer from the
hash table did not decrement its refcount. As a result, the timer was
only stopped when eos-metrics-instrumentation exits and falls off the
bus (at which point eos-event-recorder-daemon cleans up its timers).
Fix this, and make some other superficial tweaks.
https://phabricator.endlessm.com/T33295

Correctly stop session timers

---

src/eins-hwinfo.c
src/eins-hwinfo.h
src/eos-crash-metrics.c
src/eos-metrics-instrumentation.c
tests/test-hwinfo.c
tools/eos-label-location.in

I added an assertion in #104 which turns out to fail and abort the process whenever the GDM greeter quits.
This PR fixes the logic error, softens the assertion to a more detailed warning (rationale in commit message) and updates some © messages.
https://phabricator.endlessm.com/T33295

Fix assertion failure after user logs in

---

src/eins-hwinfo.c

In the Autotools build system (removed in
2751d4a329df06f573cacf455b5fc5801a7cec9a) there was a trailing slash on
INSTRUMENTATION_CACHE_DIR. In the Meson build system (added in
96dab569cfe4c11b6f6a5ae59713c396bfd9e62e) there is not. As a result,
this daemon has been writing to
/var/cache/eos-metrics-instrumentationrecord_time rather than
/var/cache/eos-metrics-instrumentation/record_time.
Fix this by adding a separator when the strings are concatenated.
Because this change has not entered a stable release of Endless OS, I'm
not going to worry about deleting or moving the erroneous file.
https://phabricator.endlessm.com/T33592

hwinfo: Fix path to record_time file

---

data/eos-metrics-instrumentation.service.in

This applies to the main daemon, not the coredump handler.
I have been running with this change locally for some time and have
noticed no adverse effects. An unprivileged user can receive systemd's
signals about startup finishind and users logging in and out, and
execute `lscpu --json` with no difference in output.
Perhaps in the past there was a reason to run as root, but no longer.
https://phabricator.endlessm.com/T9267

Run as metrics user, not root

---

.gitignore
debian/control

systemd.pc, which is used to look up the paths to install a systemd unit, tmpfiles.d snippet and sysctl.d snippet, is part of this package.
When we updated systemd in EOS 6, we dropped our patch for the the `systemd` binary package in previous branches which marked it as `Priority: required`, instead leaving it as `Priority: important`. When it was `required`, it would always be present in the buildroot, and so would `systemd-dev` which it (surprisingly!) depends on; but now it is not. 
Explicitly declare this build dependency, as we should have been doing all along.
Also add a `.gitignore`. My bad for removing it in 6eb0bbd but in my defence the version I removed didn't ignore these files.
https://phabricator.endlessm.com/T35070#990194
https://phabricator.endlessm.com/T35352

debian: Build-depend on systemd-dev
